import { validateGambleCatalog, type GambleCatalogEntry } from "./catalog";

const rawCatalog = [
  {
    id: "ballot-rps",
    title: "Ballot RPS",
    summary: "A tutorial duel where a public vote shapes the card pool before both players commit and reveal one hidden play.",
    mechanism: "Card pool, rock-paper-scissors, social signal reading",
    players: "2 duelists plus simulated voters",
    hiddenInfo: ["Private three-card hands", "Vote-pool bias", "Possible spectator signals"],
    aiHooks: ["Bayesian pool estimation", "Mixed strategy selection", "Signal-collusion suspicion"],
    fairnessHooks: ["Vote commitments", "Seeded draw replay", "Simultaneous play commit/reveal"],
    phase: "phase-2",
    complexity: 2,
    zkPriority: "high",
    readiness: "core-mvp"
  },
  {
    id: "mirror-memory",
    title: "Mirror Memory",
    summary: "A paired-card memory table where audit evidence can distinguish strong recall from marked-card advantage.",
    mechanism: "Memory matching, imperfect information, pattern anomaly detection",
    players: "2 players",
    hiddenInfo: ["Unrevealed card faces", "Possible card-back markings"],
    aiHooks: ["Coordinate memory map", "Suspicious recall model", "Intentional mistake pacing"],
    fairnessHooks: ["Deck commitment", "Reveal proofs", "Hit-rate anomaly audit"],
    phase: "future",
    complexity: 2,
    zkPriority: "medium",
    readiness: "expansion"
  },
  {
    id: "blade-roulette",
    title: "Blade Roulette",
    summary: "A virtual roulette variant where directional dice land on numbered sectors and audit tools detect biased outcomes.",
    mechanism: "Roulette, multiplier settlement, biased-randomness detection",
    players: "Dealer plus one or more bettors",
    hiddenInfo: ["Dealer bias parameters", "True landing distribution"],
    aiHooks: ["Expected-value calculator", "Dealer bias model", "Bayesian bias detector"],
    fairnessHooks: ["VRF-ready rolls", "Seed replay", "Outcome distribution audit"],
    phase: "future",
    complexity: 3,
    zkPriority: "medium",
    readiness: "research"
  },
  {
    id: "forehead-poker",
    title: "Forehead Poker",
    summary: "A four-player imperfect-information poker table driven by visible opponent cards, hidden self cards, and debt-style pressure.",
    mechanism: "Simplified poker, imperfect information, multi-player collusion",
    players: "4 players",
    hiddenInfo: ["Own hidden card", "Opponent intent", "Possible table signals"],
    aiHooks: ["Second-order belief model", "Collusion table model", "Pressure-aware betting"],
    fairnessHooks: ["Deck commitment", "Private hand proofs", "Action-log replay"],
    phase: "future",
    complexity: 4,
    zkPriority: "high",
    readiness: "research"
  },
  {
    id: "symbol-sequence",
    title: "Symbol Sequence",
    summary: "Players predict a hidden symbol order while risk pressure is represented as virtual stress rather than harm.",
    mechanism: "Sequence prediction, risk commitment, dealer trust",
    players: "2 players plus dealer",
    hiddenInfo: ["Dealer sequence", "Opponent risk tolerance"],
    aiHooks: ["Sequence prediction", "Risk commitment modeling", "Dealer trust scoring"],
    fairnessHooks: ["Sequence precommitment", "VRF-ready sequence generation", "Score replay"],
    phase: "future",
    complexity: 2,
    zkPriority: "high",
    readiness: "expansion"
  },
  {
    id: "stage-grid",
    title: "Stage Grid",
    summary: "A 3x3 board duel where mini-challenges decide marks while audience influence is audited separately.",
    mechanism: "Tic-tac-toe control, mini-challenges, audience sentiment",
    players: "2 captains plus simulated audience",
    hiddenInfo: ["Opponent skill profile", "Question pool", "Audience sentiment"],
    aiHooks: ["Optimal grid play", "Skill profile selection", "Audience model"],
    fairnessHooks: ["Challenge randomization", "Question commitments", "Vote nullifier placeholder"],
    phase: "future",
    complexity: 3,
    zkPriority: "medium",
    readiness: "research"
  },
  {
    id: "choice-draw-poker",
    title: "Choice Draw Poker",
    summary: "A draw-poker pressure duel where the bigger bettor can decide whether strong or weak hands win.",
    mechanism: "Draw poker, hand inversion, bankroll pressure",
    players: "2 players",
    hiddenInfo: ["Opponent hand", "Bankroll ceiling", "Raise intent"],
    aiHooks: ["Imperfect-information poker", "Bankroll pressure model", "Hand inversion search"],
    fairnessHooks: ["Deck commitment", "Exchange replay", "Private hand comparison proof target"],
    phase: "phase-8",
    complexity: 5,
    zkPriority: "high",
    readiness: "research"
  },
  {
    id: "fate-spread",
    title: "Fate Spread",
    summary: "A narrative card-spread boss format based on upright/reversed scoring and trust-map pressure.",
    mechanism: "Card draw, orientation scoring, narrative trust",
    players: "2 players plus final arbiter",
    hiddenInfo: ["Deck order", "Arbiter intent", "Trust-map weights"],
    aiHooks: ["Trust graph model", "Risk escalation", "Narrative pressure pacing"],
    fairnessHooks: ["Deck precommitment", "Orientation replay", "Score audit"],
    phase: "future",
    complexity: 3,
    zkPriority: "medium",
    readiness: "research"
  },
  {
    id: "pressure-shear",
    title: "Pressure Shear",
    summary: "A non-harm courage game converted into reputation pressure, withdrawal thresholds, and safety-device auditing.",
    mechanism: "Chicken game, withdrawal timing, safety integrity",
    players: "2 to 4 players",
    hiddenInfo: ["Safety switch state", "Opponent withdrawal threshold"],
    aiHooks: ["Courage threshold model", "Bluff detector", "Safety suspicion model"],
    fairnessHooks: ["Safety-state commitment", "Action replay", "Tamper anomaly audit"],
    phase: "future",
    complexity: 3,
    zkPriority: "medium",
    readiness: "research"
  },
  {
    id: "civic-guess",
    title: "Civic Guess",
    summary: "A compact political-contract event built around a high-stakes hidden binary guess.",
    mechanism: "Binary guess, contract leverage, reputation swing",
    players: "2 players",
    hiddenInfo: ["Counterparty contract intent", "Hidden guess"],
    aiHooks: ["Contract valuation", "Bluff pressure", "Binary predictor"],
    fairnessHooks: ["Guess commitment", "Synchronous reveal", "Replay hash"],
    phase: "future",
    complexity: 1,
    zkPriority: "medium",
    readiness: "prototype"
  },
  {
    id: "zero-nim",
    title: "Zero Nim",
    summary: "A card-based Nim duel with 0-3 cards, betting pressure, bust thresholds, and audit-only collusion signals.",
    mechanism: "Nim, betting layer, bust threshold",
    players: "2 to 4 players",
    hiddenInfo: ["Private cards", "Raise intent", "Possible partner signals"],
    aiHooks: ["Bust probability", "Raise pressure", "Collusion anomaly scoring"],
    fairnessHooks: ["Deal commitment", "Card-play proof placeholder", "Betting log replay"],
    phase: "phase-3",
    complexity: 3,
    zkPriority: "high",
    readiness: "core-mvp"
  },
  {
    id: "stage-63",
    title: "Stage 63",
    summary: "A performance-and-guessing team contest centered on approaching a target score without crossing it.",
    mechanism: "Performance estimate, bluffing, target approach",
    players: "Teams of 2",
    hiddenInfo: ["Performer capacity", "Food/count estimates", "Opponent confidence"],
    aiHooks: ["Target approach solver", "Expression read model", "Team coordination"],
    fairnessHooks: ["Challenge seed", "Prompt commitments", "Score replay"],
    phase: "future",
    complexity: 3,
    zkPriority: "low",
    readiness: "research"
  },
  {
    id: "greater-good",
    title: "Greater Good",
    summary: "A five-player public-goods game with hidden contribution commitments, doubled common pool, betrayal, and elimination votes.",
    mechanism: "Public goods, betrayal, anonymous voting",
    players: "5 players",
    hiddenInfo: ["Private contribution", "Alliance intent", "Elimination vote"],
    aiHooks: ["Tit-for-tat cooperation", "Defector camouflage", "Alliance domination", "Audit advocacy"],
    fairnessHooks: ["Contribution commit/reveal", "Range proof target", "Vote nullifier placeholder"],
    phase: "phase-4",
    complexity: 3,
    zkPriority: "highest",
    readiness: "core-mvp"
  },
  {
    id: "door-tower",
    title: "Door Tower",
    summary: "A spatial race puzzle using committed map topology and route inference instead of a flat card table.",
    mechanism: "Spatial puzzle, route search, race pressure",
    players: "2 players or teams",
    hiddenInfo: ["Map topology", "Opponent route", "Hidden door constraints"],
    aiHooks: ["Graph search", "Constraint solving", "Route misdirection"],
    fairnessHooks: ["Map seed commitment", "Topology hash", "Postgame reveal"],
    phase: "phase-8",
    complexity: 5,
    zkPriority: "medium",
    readiness: "expansion"
  },
  {
    id: "all-pay-vote-auction",
    title: "All-pay Vote Auction",
    summary: "A sealed-bid auction where everyone pays their bid, winner receives voting power, and hidden shill bidders are auditable.",
    mechanism: "Sealed bid, all-pay auction, budget warfare",
    players: "3 to 6 bidders",
    hiddenInfo: ["Private bids", "Budget thresholds", "Possible hidden bidder"],
    aiHooks: ["Budget management", "Shill detection", "Alliance rotation", "Overbid punishment"],
    fairnessHooks: ["Bid commit/reveal", "Highest-bid proof target", "Registered bidder set"],
    phase: "phase-8",
    complexity: 3,
    zkPriority: "highest",
    readiness: "expansion"
  },
  {
    id: "final-coin",
    title: "Final Coin",
    summary: "A compact endgame event that demonstrates fair randomness through a single high-visibility coin flip.",
    mechanism: "Single random event, final wager",
    players: "2 players",
    hiddenInfo: ["Risk appetite", "Final wager intent"],
    aiHooks: ["Risk threshold", "Endgame value model"],
    fairnessHooks: ["Dual-seed coin flip", "VRF-ready randomness", "Replay proof"],
    phase: "future",
    complexity: 1,
    zkPriority: "medium",
    readiness: "prototype"
  },
  {
    id: "speed-ranking",
    title: "Speed Ranking",
    summary: "A fast climbing-card tutorial with rank exchange pressure and tempo-focused choices.",
    mechanism: "Climbing cards, pass pressure, rank exchange",
    players: "3 to 5 players",
    hiddenInfo: ["Opponent hand", "Tempo plan"],
    aiHooks: ["Tempo heuristic", "Hand shedding priority", "Rank exchange valuation"],
    fairnessHooks: ["Deck seed replay", "Pass/action log", "Hand reveal audit"],
    phase: "future",
    complexity: 2,
    zkPriority: "low",
    readiness: "prototype"
  },
  {
    id: "three-hit-dice",
    title: "Three-hit Dice",
    summary: "A compact sequence-betting lesson based on non-intuitive pattern odds.",
    mechanism: "Pattern race, sequence selection, probability trap",
    players: "2 players",
    hiddenInfo: ["Opponent selected sequence"],
    aiHooks: ["Pattern counter-selection", "Probability explainer"],
    fairnessHooks: ["Sequence commitment", "Seeded dice stream", "Replay proof"],
    phase: "future",
    complexity: 1,
    zkPriority: "medium",
    readiness: "prototype"
  },
  {
    id: "nontransitive-dice",
    title: "Nontransitive Dice",
    summary: "A probability tutorial where dice dominance cycles make second-pick advantage detectable and explainable.",
    mechanism: "Non-transitive odds, dealer advantage, counter-pick",
    players: "2 players plus dealer",
    hiddenInfo: ["Dealer pick order intent"],
    aiHooks: ["Dominance graph", "Counter-pick selection", "Dealer advantage detector"],
    fairnessHooks: ["Die set commitment", "Seeded rolls", "Outcome replay"],
    phase: "phase-8",
    complexity: 1,
    zkPriority: "medium",
    readiness: "expansion"
  },
  {
    id: "pairing-party",
    title: "Pairing Party",
    summary: "A social deduction match where hidden pair selections, leaked information, and insider behavior shape the payoff.",
    mechanism: "Matching game, hidden choices, insider inference",
    players: "6 to 10 players",
    hiddenInfo: ["Private pairing choice", "Insider information", "Alliance promises"],
    aiHooks: ["Social graph inference", "Insider deception", "Promise tracking"],
    fairnessHooks: ["Choice commitment", "Synchronous reveal", "Identity nullifier placeholder"],
    phase: "future",
    complexity: 4,
    zkPriority: "high",
    readiness: "research"
  },
  {
    id: "parity-dice",
    title: "Parity Dice",
    summary: "A short cheating-detection drill around odd/even guesses and suspicious die replacement.",
    mechanism: "Parity guess, die swap suspicion, short duel",
    players: "2 players",
    hiddenInfo: ["True die identity", "Dealer swap timing"],
    aiHooks: ["Parity predictor", "Swap anomaly detector"],
    fairnessHooks: ["Die commitment", "Seeded roll", "Device-swap audit flag"],
    phase: "future",
    complexity: 1,
    zkPriority: "medium",
    readiness: "prototype"
  },
  {
    id: "relic-hunt",
    title: "Relic Hunt",
    summary: "A team spatial search mode with map decoding, committed treasure placement, and race pressure.",
    mechanism: "Map decoding, spatial search, team race",
    players: "Teams of 2 to 4",
    hiddenInfo: ["Treasure location", "Opponent route", "Decoded clue priority"],
    aiHooks: ["Map memory", "Route planning", "Clue prioritization", "Misdirection"],
    fairnessHooks: ["Map seed commitment", "Treasure hash", "Postgame reveal"],
    phase: "phase-8",
    complexity: 4,
    zkPriority: "medium",
    readiness: "expansion"
  },
  {
    id: "dice-nim",
    title: "Dice Nim",
    summary: "A short Nim variant where dice introduce auditable randomness and optional cheating pressure.",
    mechanism: "Nim variant, random modifier, open cheating layer",
    players: "2 players",
    hiddenInfo: ["Private threshold", "Cheat timing"],
    aiHooks: ["Nim solver", "Random modifier valuation", "Cheat-risk detector"],
    fairnessHooks: ["Seeded dice", "Move replay", "Cheat disclosure audit"],
    phase: "future",
    complexity: 2,
    zkPriority: "medium",
    readiness: "prototype"
  }
] satisfies GambleCatalogEntry[];

export const gambleCatalog = validateGambleCatalog(rawCatalog);
